### ISSUE TITLE
Falsy 'Mismatched indentation' warnings reported on files with Windows line endings 

### ISSUE THREAD

**Issue by pphunor** [cheap-glitch/eslint-plugin-smarter-tabs#3]
Empty lines aren't detected in case of Windows line endings (CR+LF).
```
class X {
	constructor() {
		this.a = 1
		this.b = 1 //<---- OK

		this.c = 1 //<---- Mismatched indentation
	}
}
```

**Comment by cheap-glitch** [comment]
Thanks for the bug report, I'll look into this.
By "Windows line endings", you mean `\r\n` instead of plain `\n`, right?

**Comment by cheap-glitch** [comment]
I couldn't reproduce the issue, but I still pushed a possible fix. Please upgrade to `v1.1.2` and tell me if the bug is still there.
